--Create tables
CREATE TABLE IF NOT EXISTS Users(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	name text, rank_id int);

CREATE TABLE IF NOT EXISTS Ranks(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text UNIQUE);

CREATE TABLE IF NOT EXISTS Parameters(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	station_high int NOT NULL, 
	temperature float CHECK(temperature <= 58 AND temperature >= -58) NOT NULL, 
	pressure int CHECK(pressure <= 900 AND pressure >= 500) NOT NULL, 
	wind_direction float CHECK(wind_direction <= 59 AND wind_direction >= 0) NOT NULL, 
	wind_speed float DEFAULT Null,
	bullet_drift int CHECK(bullet_drift <= 150 AND bullet_drift >= 0)  DEFAULT Null
	);

CREATE TABLE IF NOT EXISTS Equipments(id int GENERATED BY DEFAULT  AS IDENTITY PRIMARY KEY,
	name text UNIQUE);

CREATE TABLE IF NOT EXISTS Logs(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int NOT NULL, parametr_id int NOT NULL, 
	equipment_id int NOT NULL, date timestamp DEFAULT CURRENT_TIMESTAMP);


--TEST DATA GENERATE
INSERT INTO Ranks(name) VALUES 
	('Рядовой'),
	('Ефрейтор'),
	('Младший сержант'),
	('Сержант'),
	('Старший сержант'),
	('Старшина'),
	('Прапорщик'),
	('Старший прапорщик')
	ON CONFLICT(name) DO NOTHING;

INSERT INTO Users(id, name, rank_id) VALUES
	(1,'Волков Дмитрий Андреевич',1),
	(2,'Кузнецова Елена Игоревна',3),
	(3,'Смирнов Максим Витальевич',2),
	(4,'Морозова Анна Дмитриевна',6),
	(5,'Петров Роман Сергеевич',5)
	ON CONFLICT(id) DO NOTHING;

INSERT INTO Parameters(id, station_high, temperature, pressure, wind_direction, wind_speed) VALUES 
	(1, 150, 30.4, 700, 25.9, 12),
	(2, 160, 25.4, 654, 22.9, 9)
	ON CONFLICT(id) DO NOTHING;

INSERT INTO Parameters(id, station_high, temperature, pressure, wind_direction, bullet_drift) VALUES 
	(3, 50, 3.4, 720, 2.9, 25),
	(4, 60, 2.4, 554, 32.9, 30)
	ON CONFLICT(id) DO NOTHING;

INSERT INTO Equipments(name) VALUES
	('ДМК'),
	('ВР')
	ON CONFLICT(name) DO NOTHING;

INSERT INTO Logs(id, user_id, parametr_id, equipment_id) VALUES
	(1,1,1,1),
	(2,2,2,1),
	(3,3,3,2),
	(4,4,4,2)
	ON CONFLICT(id) DO NOTHING;

--Update ids counter
SELECT setval('users_id_seq', (SELECT MAX(id) FROM Users));
SELECT setval('parameters_id_seq', (SELECT MAX(id) FROM Parameters));
SELECT setval('logs_id_seq', (SELECT MAX(id) FROM Logs));
SELECT setval('equipments_id_seq', (SELECT MAX(id) FROM Equipments));
SELECT setval('ranks_id_seq', (SELECT MAX(id) FROM Ranks));


--Select query
SELECT *
FROM Logs
INNER JOIN Users ON Users.id = Logs.user_id
INNER JOIN Parameters ON Parameters.id = logs.parametr_id
INNER JOIN Equipments ON Equipments.id = logs.equipment_id
INNER JOIN Ranks ON Ranks.id = users.rank_id;