-- Таблицы:
--   Ranks - Звания
--   Users - пользователи (rank_id -> Ranks.id)
--   Equipments - типы оборудования (ДМК / ВР)
--   Parameters - параметры измерений
--   Logs - пачки измерений (Logs.user_id -> Users.id, Logs.parametr_id -> Parameters.id, Logs.equipment_id -> Equipments.id)


--Create tables
CREATE TABLE IF NOT EXISTS Users(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	name text, rank_id int);

CREATE TABLE IF NOT EXISTS Ranks(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text UNIQUE);

CREATE TABLE IF NOT EXISTS Parameters(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	station_high int NOT NULL, 
	temperature float CHECK(temperature <= 58 AND temperature >= -58) NOT NULL, 
	pressure int CHECK(pressure <= 900 AND pressure >= 500) NOT NULL, 
	wind_direction int CHECK(wind_direction <= 59 AND wind_direction >= 0) NOT NULL, 
	wind_speed int CHECK(wind_speed <= 15 AND wind_speed >= 0) DEFAULT Null,
	bullet_drift int CHECK(bullet_drift <= 150 AND bullet_drift >= 0)  DEFAULT Null
	);

CREATE TABLE IF NOT EXISTS Equipments(id int GENERATED BY DEFAULT  AS IDENTITY PRIMARY KEY,
	name text UNIQUE);

CREATE TABLE IF NOT EXISTS Logs(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int NOT NULL, parametr_id int NOT NULL, 
	equipment_id int NOT NULL, date timestamp DEFAULT CURRENT_TIMESTAMP);

--Comments for Tables

COMMENT ON TABLE Ranks IS 'Список званий пользователей';
COMMENT ON TABLE Users IS 'Пользователи системы; rank_id ссылается на Ranks';
COMMENT ON TABLE Equipments IS 'Типы оборудования для измерений (ДМК, ВР)';
COMMENT ON TABLE Parameters IS 'Параметры измерений с диапазонами и единицами';
COMMENT ON TABLE Logs IS 'Пачки измерений; связывает пользователя, параметры и оборудование';

--Comments for Colums

--Parameters
COMMENT ON COLUMN Parameters.id IS 'Уникальный код параметров';

COMMENT ON COLUMN Parameters.station_high IS 'Целые числа. Высота метеопоста, м над уровнем моря';

COMMENT ON COLUMN Parameters.temperature  IS 'Дробные числа. Температура воздуха, °C';
COMMENT ON CONSTRAINT parameters_temperature_check ON Parameters IS 'Температура в пределах -58..58 °C';

COMMENT ON COLUMN Parameters.pressure IS 'Целые числа. Давление атмосферы, мм рт.ст.';
COMMENT ON CONSTRAINT parameters_pressure_check ON Parameters IS 'Давление в пределах 500..900 мм рт.ст.';

COMMENT ON COLUMN Parameters.wind_direction IS 'Целые числа. Направление ветра, деления угломера';
COMMENT ON CONSTRAINT parameters_wind_direction_check ON Parameters IS 'Направление ветра в пределах 0..59';

COMMENT ON COLUMN Parameters.wind_speed IS 'Целые числа. Скорость ветра, м/с, для ДМК';
COMMENT ON CONSTRAINT parameters_wind_speed_check ON Parameters IS 'Скорость ветра в пределах 0..15 м/с';

COMMENT ON COLUMN Parameters.bullet_drift IS 'Целые числа. Дальность сноса пуль, м, для ВР';
COMMENT ON CONSTRAINT parameters_bullet_drift_check ON Parameters IS 'Снос пуль в пределах 0..150 м';

--Users
COMMENT ON COLUMN Users.id IS 'Уникальный код пользователя';
COMMENT ON COLUMN Users.name IS 'ФИО пользователя';
COMMENT ON COLUMN Users.rank_id IS 'Звание (связь на Ranks.id)';

--Logs
COMMENT ON COLUMN Logs.id IS 'Уникальный код пачки измерений';
COMMENT ON COLUMN Logs.user_id IS 'Пользователь, выполнивший измерение';
COMMENT ON COLUMN Logs.parametr_id IS 'Параметры измерения';
COMMENT ON COLUMN Logs.equipment_id IS 'Использованное оборудование (ДМК/ВР)';
COMMENT ON COLUMN Logs.date IS 'Дата и время измерения (При отсутствии ставиться автоматически)';

--Ranks
COMMENT ON COLUMN Ranks.id IS 'Уникальный код звания';
COMMENT ON COLUMN Ranks.name IS 'Название звания';

--Equipments
COMMENT ON COLUMN Equipments.id IS 'Уникальный код оборудования';
COMMENT ON COLUMN Equipments.name IS 'Название оборудования';

--TEST DATA GENERATE
INSERT INTO Ranks(name) VALUES 
	('Рядовой'),
	('Ефрейтор'),
	('Младший сержант'),
	('Сержант'),
	('Старший сержант'),
	('Старшина'),
	('Прапорщик'),
	('Старший прапорщик')
	ON CONFLICT(name) DO NOTHING;

INSERT INTO Users(id, name, rank_id) VALUES
	(1,'Волков Дмитрий Андреевич',1),
	(2,'Кузнецова Елена Игоревна',3),
	(3,'Смирнов Максим Витальевич',2),
	(4,'Морозова Анна Дмитриевна',6),
	(5,'Петров Роман Сергеевич',5)
	ON CONFLICT(id) DO NOTHING;

INSERT INTO Parameters(id, station_high, temperature, pressure, wind_direction, wind_speed) VALUES 
	(1, 150, 30.4, 700, 15, 12),
	(2, 160, 25.4, 654, 12, 9)
	ON CONFLICT(id) DO NOTHING;

INSERT INTO Parameters(id, station_high, temperature, pressure, wind_direction, bullet_drift) VALUES 
	(3, 50, 3.4, 720, 2, 25),
	(4, 60, 2.4, 554, 5, 30)
	ON CONFLICT(id) DO NOTHING;

INSERT INTO Equipments(name) VALUES
	('ДМК'),
	('ВР')
	ON CONFLICT(name) DO NOTHING;

INSERT INTO Logs(id, user_id, parametr_id, equipment_id) VALUES
	(1,1,1,1),
	(2,2,2,1),
	(3,3,3,2),
	(4,4,4,2)
	ON CONFLICT(id) DO NOTHING;

--Update ids counter
SELECT setval('users_id_seq', (SELECT MAX(id) FROM Users));
SELECT setval('parameters_id_seq', (SELECT MAX(id) FROM Parameters));
SELECT setval('logs_id_seq', (SELECT MAX(id) FROM Logs));
SELECT setval('equipments_id_seq', (SELECT MAX(id) FROM Equipments));
SELECT setval('ranks_id_seq', (SELECT MAX(id) FROM Ranks));


--Select query
SELECT *
FROM Logs
INNER JOIN Users ON Users.id = Logs.user_id
INNER JOIN Parameters ON Parameters.id = logs.parametr_id
INNER JOIN Equipments ON Equipments.id = logs.equipment_id
INNER JOIN Ranks ON Ranks.id = users.rank_id;