
ALTER TABLE Ranks
ALTER COLUMN name TYPE character varying(255);

create table Types_parameters(
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name character varying(255)
);

COMMENT ON TABLE Types_parameters IS 'Справочник типов параметров (наименования измеряемых величин)';

COMMENT ON COLUMN Types_parameters.id IS 'Уникальный код типа параметра';
COMMENT ON COLUMN Types_parameters.name IS 'Наименование параметра (высота метеопоста, температура, давление и др.)';

insert into Types_parameters(id, name) values
	(1, 'Высота метеопоста'),
	(2, 'Температура'),
	(3, 'Давление'),
	(4, 'Направление ветра'),
	(5, 'Скорость ветра'),
	(6, 'Дальность сноса пуль');

create table Units_measurement(
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name character varying(255)
);

COMMENT ON TABLE Units_measurement IS 'Справочник единиц измерения параметров';

COMMENT ON COLUMN Units_measurement.id IS 'Уникальный код единицы измерения';
COMMENT ON COLUMN Units_measurement.name IS 'Наименование единицы измерения (м, мм рт. ст., °C, градусы, м/с)';

insert into Units_measurement(id, name) values
	(1, 'Метры'),
	(2, 'мм. рт. ст.'),
	(3, 'Цельсии'),
	(4, 'Градусы'),
	(5, 'м/с');

create table Measurment_input_params
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	log_id integer,
	param_id integer,
	units_id integer,
	value decimal
);

COMMENT ON TABLE Measurment_input_params IS 'Значения параметров измерения';

COMMENT ON COLUMN Measurment_input_params.id IS 'Уникальный код записи измерения';
COMMENT ON COLUMN Measurment_input_params.log_id IS 'Номер пачки измерения (связь с Logs.id)';
COMMENT ON COLUMN Measurment_input_params.param_id IS 'Тип параметра (связь с Types_parameters.id)';
COMMENT ON COLUMN Measurment_input_params.units_id IS 'Единица измерения значения (связь с Units_measurement.id)';
COMMENT ON COLUMN Measurment_input_params.value IS 'Числовое значение параметра';


insert into measurment_input_params(log_id, units_id, param_id, value) 
	SELECT Logs.id, 1, 1, Parameters.station_high FROM Parameters JOIN Logs ON Logs.parametr_id = Parameters.id;

insert into measurment_input_params(log_id, units_id, param_id, value) 
	SELECT Logs.id, 3, 2, Parameters.temperature FROM Parameters JOIN Logs ON Logs.parametr_id = Parameters.id;

insert into measurment_input_params(log_id, units_id, param_id, value) 
	SELECT Logs.id, 2, 3, Parameters.pressure FROM Parameters JOIN Logs ON Logs.parametr_id = Parameters.id;

insert into measurment_input_params(log_id, units_id, param_id, value) 
	SELECT Logs.id, 4, 4, Parameters.wind_direction FROM Parameters JOIN Logs ON Logs.parametr_id = Parameters.id;

insert into measurment_input_params(log_id, units_id, param_id, value) 
	SELECT Logs.id, 5, 5, Parameters.wind_speed FROM Parameters JOIN Logs ON Logs.parametr_id = Parameters.id WHERE Parameters.wind_speed IS NOT NULL;

insert into measurment_input_params(log_id, units_id, param_id, value) 
	SELECT Logs.id, 1, 6, Parameters.bullet_drift FROM Parameters JOIN Logs ON Logs.parametr_id = Parameters.id WHERE Parameters.bullet_drift IS NOT NULL;

	
DROP TABLE Parameters;

ALTER TABLE Logs 
DROP COLUMN parametr_id;

select Logs.date, Logs.id, Users.name, types_parameters.name, units_measurement.name, measurment_input_params.value
from types_parameters, units_measurement, Logs, measurment_input_params, Equipments, users, ranks
where
		measurment_input_params.param_id = types_parameters.id
	and measurment_input_params.units_id = units_measurement.id
	and Users.id = Logs.user_id
	and Users.rank_id = ranks.id
	and Equipments.id = Logs.equipment_id
	and measurment_input_params.log_id = Logs.id
	order by Logs.id;
	