-- Перевод старых столбцов к ANSI-92
ALTER TABLE Ranks ALTER COLUMN name SET DATA TYPE character varying(255);
ALTER TABLE Users ALTER COLUMN name SET DATA TYPE character varying(255);
ALTER TABLE Equipments ALTER COLUMN name SET DATA TYPE character varying(255);

--Добавление новых таблиц
CREATE TABLE Types_parameters (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255)
);

CREATE TABLE Units_measurement (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255)
);

COMMENT ON TABLE Types_parameters IS 'Справочник типов (наименований) измеряемых параметров';
COMMENT ON COLUMN Types_parameters.id IS 'Уникальный код типа параметра';
COMMENT ON COLUMN Types_parameters.name IS 'Наименование измеряемого параметра';

COMMENT ON TABLE Units_measurement IS 'Справочник единиц измерения параметров';
COMMENT ON COLUMN Units_measurement.id IS 'Уникальный код единицы измерения';
COMMENT ON COLUMN Units_measurement.name IS 'Наименование единицы измерения';

COMMENT ON TABLE Parameters IS 'Значения параметров измерений';

--Заполнение новых таблиц
INSERT INTO Units_measurement (id, name) VALUES
    (1, 'Метры'),
    (2, 'мм. рт. ст.'),
    (3, 'Цельсий'),
    (4, 'Градусы'),
    (5, 'м/с');

INSERT INTO Types_parameters (id, name) VALUES
    (1, 'Высота метеопоста'),
    (2, 'Температура'),
    (3, 'Давление'),
    (4, 'Направление ветра'),
    (5, 'Скорость ветра'),
    (6, 'Дальность сноса пуль');

--Добавление новых колонок в таблицу Parameters
ALTER TABLE Parameters ADD COLUMN log_id integer;
ALTER TABLE Parameters ADD COLUMN param_id integer;
ALTER TABLE Parameters ADD COLUMN units_id integer;
ALTER TABLE Parameters ADD COLUMN param_value decimal;

COMMENT ON COLUMN Parameters.id IS 'Уникальный код записи измерения';
COMMENT ON COLUMN Parameters.log_id IS 'Номер пачки измерения';
COMMENT ON COLUMN Parameters.param_id IS 'Тип параметра';
COMMENT ON COLUMN Parameters.units_id IS 'Единица измерения значения';
COMMENT ON COLUMN Parameters.param_value IS 'Числовое значение параметра, выраженное в единицах units_id';

--Убираем ограничение старых колонок, чтобы перенести данные в новую структуру
ALTER TABLE Parameters ALTER COLUMN station_high DROP NOT NULL;
ALTER TABLE Parameters ALTER COLUMN temperature DROP NOT NULL;
ALTER TABLE Parameters ALTER COLUMN pressure DROP NOT NULL;
ALTER TABLE Parameters ALTER COLUMN wind_direction DROP NOT NULL;

-- Приводим старые данные к новой структуре
INSERT INTO Parameters (log_id, param_id, units_id, param_value)
    SELECT Logs.id, 1, 1, Parameters.station_high
    FROM Parameters INNER JOIN Logs ON Logs.parametr_id = Parameters.id
    WHERE Parameters.station_high IS NOT NULL;

INSERT INTO Parameters (log_id, param_id, units_id, param_value)
    SELECT Logs.id, 2, 3, Parameters.temperature
    FROM Parameters INNER JOIN Logs ON Logs.parametr_id = Parameters.id
    WHERE Parameters.station_high IS NOT NULL;

INSERT INTO Parameters (log_id, param_id, units_id, param_value)
    SELECT Logs.id, 3, 2, Parameters.pressure
    FROM Parameters INNER JOIN Logs ON Logs.parametr_id = Parameters.id
    WHERE Parameters.station_high IS NOT NULL;

INSERT INTO Parameters (log_id, param_id, units_id, param_value)
    SELECT Logs.id, 4, 4, Parameters.wind_direction
    FROM Parameters INNER JOIN Logs ON Logs.parametr_id = Parameters.id
    WHERE Parameters.station_high IS NOT NULL;

INSERT INTO Parameters (log_id, param_id, units_id, param_value)
    SELECT Logs.id, 5, 5, Parameters.wind_speed
    FROM Parameters INNER JOIN Logs ON Logs.parametr_id = Parameters.id
    WHERE Parameters.wind_speed IS NOT NULL;

INSERT INTO Parameters (log_id, param_id, units_id, param_value)
    SELECT Logs.id, 6, 1, Parameters.bullet_drift
    FROM Parameters INNER JOIN Logs ON Logs.parametr_id = Parameters.id
    WHERE Parameters.bullet_drift IS NOT NULL;

--Удаляем оставшие старые записи
DELETE FROM Parameters WHERE station_high IS NOT NULL;

--Дропаем старые колонки
ALTER TABLE Parameters DROP COLUMN station_high;
ALTER TABLE Parameters DROP COLUMN temperature;
ALTER TABLE Parameters DROP COLUMN pressure;
ALTER TABLE Parameters DROP COLUMN wind_direction;
ALTER TABLE Parameters DROP COLUMN wind_speed;
ALTER TABLE Parameters DROP COLUMN bullet_drift;

ALTER TABLE Logs DROP COLUMN parametr_id;

--Добавляем ограниение на новые колонки в Parameters
ALTER TABLE Parameters ALTER COLUMN log_id SET NOT NULL;
ALTER TABLE Parameters ALTER COLUMN param_id SET NOT NULL;
ALTER TABLE Parameters ALTER COLUMN units_id SET NOT NULL;
ALTER TABLE Parameters ALTER COLUMN param_value SET NOT NULL;

--Итоговый запрос
SELECT Logs.date, Logs.id, Users.name, types_parameters.name, units_measurement.name, Parameters.param_value
FROM types_parameters, units_measurement, Logs, Parameters, Equipments, users, ranks
WHERE
		Parameters.param_id = types_parameters.id
	AND Parameters.units_id = units_measurement.id
	AND Users.id = Logs.user_id
	AND Users.rank_id = ranks.id
	AND Equipments.id = Logs.equipment_id
	AND Parameters.log_id = Logs.id
	ORDER BY Logs.id;
